//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: login.proto
namespace Login
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginReq")]
  public partial class LoginReq : global::ProtoBuf.IExtensible
  {
    public LoginReq() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private bool _guest_mode;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"guest_mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool guest_mode
    {
      get { return _guest_mode; }
      set { _guest_mode = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _client_os;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"client_os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_os
    {
      get { return _client_os; }
      set { _client_os = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRsp")]
  public partial class LoginRsp : global::ProtoBuf.IExtensible
  {
    public LoginRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _money;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private int _extmoney;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"extmoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int extmoney
    {
      get { return _extmoney; }
      set { _extmoney = value; }
    }
    private int _usertype;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"usertype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int usertype
    {
      get { return _usertype; }
      set { _usertype = value; }
    }
    private int _err_no;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckVerReq")]
  public partial class CheckVerReq : global::ProtoBuf.IExtensible
  {
    public CheckVerReq() {}
    
    private string _client_os;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"client_os", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string client_os
    {
      get { return _client_os; }
      set { _client_os = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CheckVerRsp")]
  public partial class CheckVerRsp : global::ProtoBuf.IExtensible
  {
    public CheckVerRsp() {}
    
    private bool _guest_mode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guest_mode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool guest_mode
    {
      get { return _guest_mode; }
      set { _guest_mode = value; }
    }
    private bool _version_match;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version_match", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool version_match
    {
      get { return _version_match; }
      set { _version_match = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IOS_RegistReq")]
  public partial class IOS_RegistReq : global::ProtoBuf.IExtensible
  {
    public IOS_RegistReq() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IOS_RegistRsp")]
  public partial class IOS_RegistRsp : global::ProtoBuf.IExtensible
  {
    public IOS_RegistRsp() {}
    
    private int _errno;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errno", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errno
    {
      get { return _errno; }
      set { _errno = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}