//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: table.proto
namespace Table
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateReq")]
  public partial class CreateReq : global::ProtoBuf.IExtensible
  {
    public CreateReq() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _playoffs;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"playoffs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playoffs
    {
      get { return _playoffs; }
      set { _playoffs = value; }
    }
    private int _times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times; }
      set { _times = value; }
    }
    private int _jiangma;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"jiangma", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jiangma
    {
      get { return _jiangma; }
      set { _jiangma = value; }
    }
    private int _maima;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"maima", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maima
    {
      get { return _maima; }
      set { _maima = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateRsp")]
  public partial class CreateRsp : global::ProtoBuf.IExtensible
  {
    public CreateRsp() {}
    
    private int _tab_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tab_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tab_id
    {
      get { return _tab_id; }
      set { _tab_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinReq")]
  public partial class JoinReq : global::ProtoBuf.IExtensible
  {
    public JoinReq() {}
    
    private int _tab_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tab_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tab_id
    {
      get { return _tab_id; }
      set { _tab_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReJoinReq")]
  public partial class ReJoinReq : global::ProtoBuf.IExtensible
  {
    public ReJoinReq() {}
    
    private int _tab_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tab_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tab_id
    {
      get { return _tab_id; }
      set { _tab_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Rule")]
  public partial class Rule : global::ProtoBuf.IExtensible
  {
    public Rule() {}
    
    private int _totalround;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"totalround", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalround
    {
      get { return _totalround; }
      set { _totalround = value; }
    }
    private int _maxbet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxbet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxbet
    {
      get { return _maxbet; }
      set { _maxbet = value; }
    }
    private int _jiangma;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"jiangma", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int jiangma
    {
      get { return _jiangma; }
      set { _jiangma = value; }
    }
    private int _maima;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"maima", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maima
    {
      get { return _maima; }
      set { _maima = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReJoinRsp")]
  public partial class ReJoinRsp : global::ProtoBuf.IExtensible
  {
    public ReJoinRsp() {}
    
    private int _err_no;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private int _owner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private int _tab_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tab_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tab_id
    {
      get { return _tab_id; }
      set { _tab_id = value; }
    }
    private int _is_playing;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"is_playing", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int is_playing
    {
      get { return _is_playing; }
      set { _is_playing = value; }
    }
    private Table.Rule _rule;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Table.Rule rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.Role> _roles = new global::System.Collections.Generic.List<Table.Role>();
    [global::ProtoBuf.ProtoMember(6, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.Role> roles
    {
      get { return _roles; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.EndCards> _end_cards = new global::System.Collections.Generic.List<Table.EndCards>();
    [global::ProtoBuf.ProtoMember(7, Name=@"end_cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.EndCards> end_cards
    {
      get { return _end_cards; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.PlayerRecords> _player_record = new global::System.Collections.Generic.List<Table.PlayerRecords>();
    [global::ProtoBuf.ProtoMember(8, Name=@"player_record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PlayerRecords> player_record
    {
      get { return _player_record; }
    }
  
    private int _cur_id;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"cur_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_id
    {
      get { return _cur_id; }
      set { _cur_id = value; }
    }
    private int _cur_round;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"cur_round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_round
    {
      get { return _cur_round; }
      set { _cur_round = value; }
    }
    private int _cur_card;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"cur_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_card
    {
      get { return _cur_card; }
      set { _cur_card = value; }
    }
    private int _left_card;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"left_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int left_card
    {
      get { return _left_card; }
      set { _left_card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Join")]
  public partial class Join : global::ProtoBuf.IExtensible
  {
    public Join() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Table.Role _role;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"role", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Table.Role role
    {
      get { return _role; }
      set { _role = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JoinRsp")]
  public partial class JoinRsp : global::ProtoBuf.IExtensible
  {
    public JoinRsp() {}
    
    private int _err_no;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private int _owner;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"owner", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int owner
    {
      get { return _owner; }
      set { _owner = value; }
    }
    private Table.Rule _rule;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rule", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Table.Rule rule
    {
      get { return _rule; }
      set { _rule = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.Role> _roles = new global::System.Collections.Generic.List<Table.Role>();
    [global::ProtoBuf.ProtoMember(4, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.Role> roles
    {
      get { return _roles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SysErrorRsp")]
  public partial class SysErrorRsp : global::ProtoBuf.IExtensible
  {
    public SysErrorRsp() {}
    
    private string _err_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"err_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string err_info
    {
      get { return _err_info; }
      set { _err_info = value; }
    }
    private int _err_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_type
    {
      get { return _err_type; }
      set { _err_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuitReq")]
  public partial class QuitReq : global::ProtoBuf.IExtensible
  {
    public QuitReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuitRsp")]
  public partial class QuitRsp : global::ProtoBuf.IExtensible
  {
    public QuitRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _quit_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"quit_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int quit_type
    {
      get { return _quit_type; }
      set { _quit_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickReq")]
  public partial class KickReq : global::ProtoBuf.IExtensible
  {
    public KickReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickRsp")]
  public partial class KickRsp : global::ProtoBuf.IExtensible
  {
    public KickRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _err_no;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Role")]
  public partial class Role : global::ProtoBuf.IExtensible
  {
    public Role() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private bool _ready;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private bool _online;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool online
    {
      get { return _online; }
      set { _online = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private int _sex;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyNextReq")]
  public partial class ReadyNextReq : global::ProtoBuf.IExtensible
  {
    public ReadyNextReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyNextRsp")]
  public partial class ReadyNextRsp : global::ProtoBuf.IExtensible
  {
    public ReadyNextRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadyReq")]
  public partial class ReadyReq : global::ProtoBuf.IExtensible
  {
    public ReadyReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ready")]
  public partial class Ready : global::ProtoBuf.IExtensible
  {
    public Ready() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Start")]
  public partial class Start : global::ProtoBuf.IExtensible
  {
    public Start() {}
    
    private int _status;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _round;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"round", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round
    {
      get { return _round; }
      set { _round = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.PlayerRecords> _player_record = new global::System.Collections.Generic.List<Table.PlayerRecords>();
    [global::ProtoBuf.ProtoMember(4, Name=@"player_record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PlayerRecords> player_record
    {
      get { return _player_record; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Cards")]
  public partial class Cards : global::ProtoBuf.IExtensible
  {
    public Cards() {}
    
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Turn")]
  public partial class Turn : global::ProtoBuf.IExtensible
  {
    public Turn() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Play")]
  public partial class Play : global::ProtoBuf.IExtensible
  {
    public Play() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _leftcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"leftcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> leftcard
    {
      get { return _leftcard; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _outcards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"outcards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> outcards
    {
      get { return _outcards; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.PGData> _pgdata = new global::System.Collections.Generic.List<Table.PGData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"pgdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PGData> pgdata
    {
      get { return _pgdata; }
    }
  
    private int _err_no;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Peng")]
  public partial class Peng : global::ProtoBuf.IExtensible
  {
    public Peng() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _from;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _err_no;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.PGData> _pgdata = new global::System.Collections.Generic.List<Table.PGData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"pgdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PGData> pgdata
    {
      get { return _pgdata; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _leftcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"leftcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> leftcard
    {
      get { return _leftcard; }
    }
  
    private int _nextcard;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"nextcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int nextcard
    {
      get { return _nextcard; }
      set { _nextcard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Angang")]
  public partial class Angang : global::ProtoBuf.IExtensible
  {
    public Angang() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Gang")]
  public partial class Gang : global::ProtoBuf.IExtensible
  {
    public Gang() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _from;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _err_no;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.PGData> _pgdata = new global::System.Collections.Generic.List<Table.PGData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"pgdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PGData> pgdata
    {
      get { return _pgdata; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _leftcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"leftcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> leftcard
    {
      get { return _leftcard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Hu")]
  public partial class Hu : global::ProtoBuf.IExtensible
  {
    public Hu() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _from;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _hutype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hutype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hutype
    {
      get { return _hutype; }
      set { _hutype = value; }
    }
    private int _err_no;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private int _exttype;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exttype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exttype
    {
      get { return _exttype; }
      set { _exttype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanHu")]
  public partial class CanHu : global::ProtoBuf.IExtensible
  {
    public CanHu() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PassCountRsp")]
  public partial class PassCountRsp : global::ProtoBuf.IExtensible
  {
    public PassCountRsp() {}
    
    private string _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pass")]
  public partial class Pass : global::ProtoBuf.IExtensible
  {
    public Pass() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _auto;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"auto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool auto
    {
      get { return _auto; }
      set { _auto = value; }
    }
    private int _passcard;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"passcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int passcard
    {
      get { return _passcard; }
      set { _passcard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PassHu")]
  public partial class PassHu : global::ProtoBuf.IExtensible
  {
    public PassHu() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FixCards")]
  public partial class FixCards : global::ProtoBuf.IExtensible
  {
    public FixCards() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _leftcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"leftcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> leftcard
    {
      get { return _leftcard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewCard")]
  public partial class NewCard : global::ProtoBuf.IExtensible
  {
    public NewCard() {}
    
    private int _card;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _leftcard;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"leftcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int leftcard
    {
      get { return _leftcard; }
      set { _leftcard = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _myleftcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"myleftcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> myleftcard
    {
      get { return _myleftcard; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SwitchAuto")]
  public partial class SwitchAuto : global::ProtoBuf.IExtensible
  {
    public SwitchAuto() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _isauto;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"isauto", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isauto
    {
      get { return _isauto; }
      set { _isauto = value; }
    }
    private int _cur_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cur_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cur_id
    {
      get { return _cur_id; }
      set { _cur_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeAutoReq")]
  public partial class ChangeAutoReq : global::ProtoBuf.IExtensible
  {
    public ChangeAutoReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelAutoReq")]
  public partial class CancelAutoReq : global::ProtoBuf.IExtensible
  {
    public CancelAutoReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoiceChat")]
  public partial class VoiceChat : global::ProtoBuf.IExtensible
  {
    public VoiceChat() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _index;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QuickMsg")]
  public partial class QuickMsg : global::ProtoBuf.IExtensible
  {
    public QuickMsg() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _msgid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msgid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int msgid
    {
      get { return _msgid; }
      set { _msgid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaiMa")]
  public partial class MaiMa : global::ProtoBuf.IExtensible
  {
    public MaiMa() {}
    
    private readonly global::System.Collections.Generic.List<Table.MaiMaData> _maima_list = new global::System.Collections.Generic.List<Table.MaiMaData>();
    [global::ProtoBuf.ProtoMember(1, Name=@"maima_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.MaiMaData> maima_list
    {
      get { return _maima_list; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardsAll = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardsAll", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardsAll
    {
      get { return _cardsAll; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.MaiMaScore> _maima_score1 = new global::System.Collections.Generic.List<Table.MaiMaScore>();
    [global::ProtoBuf.ProtoMember(3, Name=@"maima_score1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.MaiMaScore> maima_score1
    {
      get { return _maima_score1; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.MaiMaScore> _maima_score2 = new global::System.Collections.Generic.List<Table.MaiMaScore>();
    [global::ProtoBuf.ProtoMember(4, Name=@"maima_score2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.MaiMaScore> maima_score2
    {
      get { return _maima_score2; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaiMaData")]
  public partial class MaiMaData : global::ProtoBuf.IExtensible
  {
    public MaiMaData() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _card1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card1
    {
      get { return _card1; }
      set { _card1 = value; }
    }
    private int _card2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card2
    {
      get { return _card2; }
      set { _card2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaiMaScore")]
  public partial class MaiMaScore : global::ProtoBuf.IExtensible
  {
    public MaiMaScore() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private int _targetid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"targetid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetid
    {
      get { return _targetid; }
      set { _targetid = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"JiangMa")]
  public partial class JiangMa : global::ProtoBuf.IExtensible
  {
    public JiangMa() {}
    
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _cardsAll = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cardsAll", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cardsAll
    {
      get { return _cardsAll; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoundScore")]
  public partial class RoundScore : global::ProtoBuf.IExtensible
  {
    public RoundScore() {}
    
    private readonly global::System.Collections.Generic.List<Table.Score> _scores = new global::System.Collections.Generic.List<Table.Score>();
    [global::ProtoBuf.ProtoMember(1, Name=@"scores", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.Score> scores
    {
      get { return _scores; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.EndCards> _end_cards = new global::System.Collections.Generic.List<Table.EndCards>();
    [global::ProtoBuf.ProtoMember(2, Name=@"end_cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.EndCards> end_cards
    {
      get { return _end_cards; }
    }
  
    private int _end_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"end_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int end_type
    {
      get { return _end_type; }
      set { _end_type = value; }
    }
    private int _round_id;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"round_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round_id
    {
      get { return _round_id; }
      set { _round_id = value; }
    }
    private string _starttime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"starttime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string starttime
    {
      get { return _starttime; }
      set { _starttime = value; }
    }
    private string _lianzhuang;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"lianzhuang", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string lianzhuang
    {
      get { return _lianzhuang; }
      set { _lianzhuang = value; }
    }
    private int _exttype;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"exttype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int exttype
    {
      get { return _exttype; }
      set { _exttype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EndCards")]
  public partial class EndCards : global::ProtoBuf.IExtensible
  {
    public EndCards() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.PGData> _pgdata = new global::System.Collections.Generic.List<Table.PGData>();
    [global::ProtoBuf.ProtoMember(3, Name=@"pgdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PGData> pgdata
    {
      get { return _pgdata; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _outcards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"outcards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> outcards
    {
      get { return _outcards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Score")]
  public partial class Score : global::ProtoBuf.IExtensible
  {
    public Score() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _hu;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"hu", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hu
    {
      get { return _hu; }
      set { _hu = value; }
    }
    private int _hu_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"hu_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hu_type
    {
      get { return _hu_type; }
      set { _hu_type = value; }
    }
    private int _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _basescore;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"basescore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int basescore
    {
      get { return _basescore; }
      set { _basescore = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _jiangma = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(6, Name=@"jiangma", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> jiangma
    {
      get { return _jiangma; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PGData")]
  public partial class PGData : global::ProtoBuf.IExtensible
  {
    public PGData() {}
    
    private int _ptype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ptype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ptype
    {
      get { return _ptype; }
      set { _ptype = value; }
    }
    private int _from;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"from", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from
    {
      get { return _from; }
      set { _from = value; }
    }
    private int _card;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card
    {
      get { return _card; }
      set { _card = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameEnd")]
  public partial class GameEnd : global::ProtoBuf.IExtensible
  {
    public GameEnd() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.PlayerRecords> _player_records = new global::System.Collections.Generic.List<Table.PlayerRecords>();
    [global::ProtoBuf.ProtoMember(2, Name=@"player_records", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.PlayerRecords> player_records
    {
      get { return _player_records; }
    }
  
    private int _index;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerRecords")]
  public partial class PlayerRecords : global::ProtoBuf.IExtensible
  {
    public PlayerRecords() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _zm_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"zm_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zm_count
    {
      get { return _zm_count; }
      set { _zm_count = value; }
    }
    private int _dp_count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dp_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dp_count
    {
      get { return _dp_count; }
      set { _dp_count = value; }
    }
    private int _hp_count;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"hp_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp_count
    {
      get { return _hp_count; }
      set { _hp_count = value; }
    }
    private int _ag_count;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"ag_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ag_count
    {
      get { return _ag_count; }
      set { _ag_count = value; }
    }
    private int _mg_count;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"mg_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mg_count
    {
      get { return _mg_count; }
      set { _mg_count = value; }
    }
    private int _mm_count;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mm_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mm_count
    {
      get { return _mm_count; }
      set { _mm_count = value; }
    }
    private int _total_score;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MoneyChange")]
  public partial class MoneyChange : global::ProtoBuf.IExtensible
  {
    public MoneyChange() {}
    
    private int _mymoney;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mymoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mymoney
    {
      get { return _mymoney; }
      set { _mymoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HeartbeatReq")]
  public partial class HeartbeatReq : global::ProtoBuf.IExtensible
  {
    public HeartbeatReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryTableReq")]
  public partial class HistoryTableReq : global::ProtoBuf.IExtensible
  {
    public HistoryTableReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _page;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryTableRsp")]
  public partial class HistoryTableRsp : global::ProtoBuf.IExtensible
  {
    public HistoryTableRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _page;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int page
    {
      get { return _page; }
      set { _page = value; }
    }
    private int _maxpage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxpage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxpage
    {
      get { return _maxpage; }
      set { _maxpage = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.HistoryTable> _table_list = new global::System.Collections.Generic.List<Table.HistoryTable>();
    [global::ProtoBuf.ProtoMember(4, Name=@"table_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.HistoryTable> table_list
    {
      get { return _table_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryTable")]
  public partial class HistoryTable : global::ProtoBuf.IExtensible
  {
    public HistoryTable() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _table_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"table_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int table_id
    {
      get { return _table_id; }
      set { _table_id = value; }
    }
    private int _owner_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"owner_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int owner_id
    {
      get { return _owner_id; }
      set { _owner_id = value; }
    }
    private string _start_time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }
    private string _end_time;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.HistoryTablePlayerinfo> _playerinfo_list = new global::System.Collections.Generic.List<Table.HistoryTablePlayerinfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"playerinfo_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.HistoryTablePlayerinfo> playerinfo_list
    {
      get { return _playerinfo_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryTablePlayerinfo")]
  public partial class HistoryTablePlayerinfo : global::ProtoBuf.IExtensible
  {
    public HistoryTablePlayerinfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _total_score;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"total_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_score
    {
      get { return _total_score; }
      set { _total_score = value; }
    }
    private string _url;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string url
    {
      get { return _url; }
      set { _url = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryTableDetailReq")]
  public partial class HistoryTableDetailReq : global::ProtoBuf.IExtensible
  {
    public HistoryTableDetailReq() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryTableDetailRsp")]
  public partial class HistoryTableDetailRsp : global::ProtoBuf.IExtensible
  {
    public HistoryTableDetailRsp() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.RoundScore> _round_score_list = new global::System.Collections.Generic.List<Table.RoundScore>();
    [global::ProtoBuf.ProtoMember(2, Name=@"round_score_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.RoundScore> round_score_list
    {
      get { return _round_score_list; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.HistoryMaiMa> _maima_list = new global::System.Collections.Generic.List<Table.HistoryMaiMa>();
    [global::ProtoBuf.ProtoMember(3, Name=@"maima_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.HistoryMaiMa> maima_list
    {
      get { return _maima_list; }
    }
  
    private readonly global::System.Collections.Generic.List<Table.HistroyJiangMa> _jiangma_list = new global::System.Collections.Generic.List<Table.HistroyJiangMa>();
    [global::ProtoBuf.ProtoMember(4, Name=@"jiangma_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.HistroyJiangMa> jiangma_list
    {
      get { return _jiangma_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistoryMaiMa")]
  public partial class HistoryMaiMa : global::ProtoBuf.IExtensible
  {
    public HistoryMaiMa() {}
    
    private int _round_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"round_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round_id
    {
      get { return _round_id; }
      set { _round_id = value; }
    }
    private readonly global::System.Collections.Generic.List<Table.MaiMaDataNew> _maima_list = new global::System.Collections.Generic.List<Table.MaiMaDataNew>();
    [global::ProtoBuf.ProtoMember(2, Name=@"maima_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.MaiMaDataNew> maima_list
    {
      get { return _maima_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistroyJiangMa")]
  public partial class HistroyJiangMa : global::ProtoBuf.IExtensible
  {
    public HistroyJiangMa() {}
    
    private int _round_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"round_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int round_id
    {
      get { return _round_id; }
      set { _round_id = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _jiangma_list = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"jiangma_list", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> jiangma_list
    {
      get { return _jiangma_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaiMaDataNew")]
  public partial class MaiMaDataNew : global::ProtoBuf.IExtensible
  {
    public MaiMaDataNew() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _card1;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"card1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card1
    {
      get { return _card1; }
      set { _card1 = value; }
    }
    private int _card2;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"card2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int card2
    {
      get { return _card2; }
      set { _card2 = value; }
    }
    private int _zhong1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"zhong1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zhong1
    {
      get { return _zhong1; }
      set { _zhong1 = value; }
    }
    private int _zhong2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"zhong2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zhong2
    {
      get { return _zhong2; }
      set { _zhong2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReconnectRsp")]
  public partial class ReconnectRsp : global::ProtoBuf.IExtensible
  {
    public ReconnectRsp() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMStopServerReq")]
  public partial class GMStopServerReq : global::ProtoBuf.IExtensible
  {
    public GMStopServerReq() {}
    
    private bool _stop;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool stop
    {
      get { return _stop; }
      set { _stop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQuerySinglePlayerReq")]
  public partial class GMQuerySinglePlayerReq : global::ProtoBuf.IExtensible
  {
    public GMQuerySinglePlayerReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQueryAgentListReq")]
  public partial class GMQueryAgentListReq : global::ProtoBuf.IExtensible
  {
    public GMQueryAgentListReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQueryPlayerListReq")]
  public partial class GMQueryPlayerListReq : global::ProtoBuf.IExtensible
  {
    public GMQueryPlayerListReq() {}
    
    private int _money;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQueryMoneyLogReq")]
  public partial class GMQueryMoneyLogReq : global::ProtoBuf.IExtensible
  {
    public GMQueryMoneyLogReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _is_active;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"is_active", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_active
    {
      get { return _is_active; }
      set { _is_active = value; }
    }
    private int _startindex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startindex
    {
      get { return _startindex; }
      set { _startindex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQuerySingleGMLogReq")]
  public partial class GMQuerySingleGMLogReq : global::ProtoBuf.IExtensible
  {
    public GMQuerySingleGMLogReq() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMAddMoneyReq")]
  public partial class GMAddMoneyReq : global::ProtoBuf.IExtensible
  {
    public GMAddMoneyReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMAddMoneyRsp")]
  public partial class GMAddMoneyRsp : global::ProtoBuf.IExtensible
  {
    public GMAddMoneyRsp() {}
    
    private int _err_no;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"err_no", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int err_no
    {
      get { return _err_no; }
      set { _err_no = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMAddAgentReq")]
  public partial class GMAddAgentReq : global::ProtoBuf.IExtensible
  {
    public GMAddAgentReq() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _yes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool yes
    {
      get { return _yes; }
      set { _yes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMPlayerInfo")]
  public partial class GMPlayerInfo : global::ProtoBuf.IExtensible
  {
    public GMPlayerInfo() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _total_money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"total_money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int total_money
    {
      get { return _total_money; }
      set { _total_money = value; }
    }
    private bool _is_agent;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"is_agent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_agent
    {
      get { return _is_agent; }
      set { _is_agent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMMoneyLog")]
  public partial class GMMoneyLog : global::ProtoBuf.IExtensible
  {
    public GMMoneyLog() {}
    
    private int _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int index
    {
      get { return _index; }
      set { _index = value; }
    }
    private int _fromid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"fromid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromid
    {
      get { return _fromid; }
      set { _fromid = value; }
    }
    private int _fromname;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fromname", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fromname
    {
      get { return _fromname; }
      set { _fromname = value; }
    }
    private int _toid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"toid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int toid
    {
      get { return _toid; }
      set { _toid = value; }
    }
    private string _toname;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"toname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string toname
    {
      get { return _toname; }
      set { _toname = value; }
    }
    private int _value;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private string _optime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"optime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string optime
    {
      get { return _optime; }
      set { _optime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMPlayerInfoRsp")]
  public partial class GMPlayerInfoRsp : global::ProtoBuf.IExtensible
  {
    public GMPlayerInfoRsp() {}
    
    private readonly global::System.Collections.Generic.List<Table.GMPlayerInfo> _player_info_list = new global::System.Collections.Generic.List<Table.GMPlayerInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"player_info_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.GMPlayerInfo> player_info_list
    {
      get { return _player_info_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMMoneyLogRsp")]
  public partial class GMMoneyLogRsp : global::ProtoBuf.IExtensible
  {
    public GMMoneyLogRsp() {}
    
    private readonly global::System.Collections.Generic.List<Table.GMMoneyLog> _money_log_list = new global::System.Collections.Generic.List<Table.GMMoneyLog>();
    [global::ProtoBuf.ProtoMember(1, Name=@"money_log_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Table.GMMoneyLog> money_log_list
    {
      get { return _money_log_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQuerySysInfoReq")]
  public partial class GMQuerySysInfoReq : global::ProtoBuf.IExtensible
  {
    public GMQuerySysInfoReq() {}
    
    private string _password;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMQuerySysInfoRsp")]
  public partial class GMQuerySysInfoRsp : global::ProtoBuf.IExtensible
  {
    public GMQuerySysInfoRsp() {}
    
    private readonly global::System.Collections.Generic.List<int> _tablelist = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"tablelist", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> tablelist
    {
      get { return _tablelist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GMDestroyRoomReq")]
  public partial class GMDestroyRoomReq : global::ProtoBuf.IExtensible
  {
    public GMDestroyRoomReq() {}
    
    private int _tabid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tabid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tabid
    {
      get { return _tabid; }
      set { _tabid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IOS_PurchaseReq")]
  public partial class IOS_PurchaseReq : global::ProtoBuf.IExtensible
  {
    public IOS_PurchaseReq() {}
    
    private int _purchase_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"purchase_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int purchase_id
    {
      get { return _purchase_id; }
      set { _purchase_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IOS_RegistReq")]
  public partial class IOS_RegistReq : global::ProtoBuf.IExtensible
  {
    public IOS_RegistReq() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IOS_RegistRsp")]
  public partial class IOS_RegistRsp : global::ProtoBuf.IExtensible
  {
    public IOS_RegistRsp() {}
    
    private int _errno;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errno", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errno
    {
      get { return _errno; }
      set { _errno = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShowOfflineRsp")]
  public partial class ShowOfflineRsp : global::ProtoBuf.IExtensible
  {
    public ShowOfflineRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _yes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool yes
    {
      get { return _yes; }
      set { _yes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoteQuitReq")]
  public partial class VoteQuitReq : global::ProtoBuf.IExtensible
  {
    public VoteQuitReq() {}
    
    private bool _yes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool yes
    {
      get { return _yes; }
      set { _yes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VoteQuitRsp")]
  public partial class VoteQuitRsp : global::ProtoBuf.IExtensible
  {
    public VoteQuitRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _yes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool yes
    {
      get { return _yes; }
      set { _yes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartVoteReq")]
  public partial class StartVoteReq : global::ProtoBuf.IExtensible
  {
    public StartVoteReq() {}
    
    private bool _yes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"yes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool yes
    {
      get { return _yes; }
      set { _yes = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartVoteRsp")]
  public partial class StartVoteRsp : global::ProtoBuf.IExtensible
  {
    public StartVoteRsp() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}